//priority: 11000
/* 
 _____                                             _____ 
( ___ ) © SanoLink 2024/2025. All rights reserved.( ___ )
 |   |~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|   | 
 |   |  _____         _     _____        ______    |   | 
 |   | |_   _|__  ___| |__ | ____|_   __ \ \ \ \   |   | 
 |   |   | |/ _ \/ __| '_ \|  _| \ \ / /  \ \ \ \  |   | 
 |   |   | |  __/ (__| | | | |___ \ V /   / / / /  |   | 
 |   |  _|_|\___|\___|_| |_|_____| \_/   /_/_/_/   |   | 
 |   | |  _ \(_)___  ___ _____   _____ _ __ _   _  |   | 
 |   | | | | | / __|/ __/ _ \ \ / / _ \ '__| | | | |   | 
 |   | | |_| | \__ \ (_| (_) \ V /  __/ |  | |_| | |   | 
 |   | |____/|_|___/\___\___/ \_/ \___|_|   \__, | |   | 
 |   |                                      |___/  |   | 
 |___|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|___| 
(_____)         Last Modification : 1.4.0         (_____)

*/

const $CropRegistry = Java.loadClass('com.blakebr0.mysticalagriculture.registry.CropRegistry')
const CropRegistryInstance = $CropRegistry.getInstance()

const SecondarySeedChance = 0.01

const mysticalCrops = {
	enabled: [
		"air",
		"earth",
		"water",
		"fire",
		"inferium",
		"stone",
		"dirt",
		"wood",
		"ice",
		"deepslate",
		"alfsteel",
		"awakened_supremium",
		"calorite",
		"chocolate",
		"cinnabar",
		"desh",
		"destabilized_redstone",
		"dragonsteel_fire",
		"dragonsteel_ice",
		"dragonsteel_lightning",
		"echo",
		"energized_glowstone",
		"iesnium",
		"imperium",
		"insanium",
		"nephryx",
		"oil",
		"ostrum",
		"peridot",
		"pink_slime",
		"plastic",
		"prudentium",
		"resonant_ender",
		"soul_steel",
		"source_gem",
		"supremium",
		"tea",
		"tertium",
		"ultimate",
		"wasted_radioactive",
		"nature",
		"dye",
		"nether",
		"coal",
		"coral",
		"honey",
		"amethyst",
		"pig",
		"chicken",
		"cow",
		"sheep",
		"squid",
		"fish",
		"slime",
		"turtle",
		"silicon",
		"sulfur",
		"aluminum",
		"saltpeter",
		"apatite",
		"mystical_flower",
		"limestone",
		"iron",
		"copper",
		"nether_quartz",
		"glowstone",
		"redstone",
		"obsidian",
		"prismarine",
		"zombie",
		"skeleton",
		"creeper",
		"spider",
		"rabbit",
		"tin",
		"bronze",
		"zinc",
		"brass",
		"silver",
		"lead",
		"blizz",
		"blitz",
		"basalz",
		"manasteel",
		"steeleaf",
		"ironwood",
		"sky_stone",
		"certus_quartz",
		"gold",
		"lapis_lazuli",
		"end",
		"experience",
		"blaze",
		"ghast",
		"enderman",
		"steel",
		"nickel",
		"constantan",
		"electrum",
		"invar",
		"uranium",
		"ruby",
		"sapphire",
		"signalum",
		"lumium",
		"hop_graphite",
		"elementium",
		"osmium",
		"fluorite",
		"refined_glowstone",
		"refined_obsidian",
		"knightmetal",
		"fiery_ingot",
		"compressed_iron",
		"fluix",
		"energized_steel",
		"blazing_crystal",
		"diamond",
		"emerald",
		"netherite",
		"wither_skeleton",
		"platinum",
		"iridium",
		"enderium",
		"terrasteel",
		"niotic_crystal",
		"spirited_crystal",
		"uraninite",
		"nether_star",
		"dragon_egg",
		"gaia_spirit",
		"nitro_crystal"
	],
	disabled: [
		"rubber",
		"marble",
		"basalt",
		"menril",
		"graphite",
		"amethyst_bronze",
		"slimesteel",
		"pig_iron",
		"aquamarine",
		"quartz_enriched_iron",
		"mithril",
		"tungsten",
		"titanium",
		"chrome",
		"flux_infused_ingot",
		"cobalt",
		"rose_gold",
		"starmetal",
		"flux_infused_gem",
		"manyullyn",
		"queens_slime",
		"hepatizon",
		"rock_crystal",
		"draconium",
		"yellorium",
		"cyanite",
		"awakened_draconium",
		"neutronium"
	]
}