/* 
 _____                                             _____ 
( ___ ) © SanoLink 2024/2025. All rights reserved.( ___ )
 |   |~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|   | 
 |   |  _____         _     _____        ______    |   | 
 |   | |_   _|__  ___| |__ | ____|_   __ \ \ \ \   |   | 
 |   |   | |/ _ \/ __| '_ \|  _| \ \ / /  \ \ \ \  |   | 
 |   |   | |  __/ (__| | | | |___ \ V /   / / / /  |   | 
 |   |  _|_|\___|\___|_| |_|_____| \_/   /_/_/_/   |   | 
 |   | |  _ \(_)___  ___ _____   _____ _ __ _   _  |   | 
 |   | | | | | / __|/ __/ _ \ \ / / _ \ '__| | | | |   | 
 |   | | |_| | \__ \ (_| (_) \ V /  __/ |  | |_| | |   | 
 |   | |____/|_|___/\___\___/ \_/ \___|_|   \__, | |   | 
 |   |                                      |___/  |   | 
 |___|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|___| 
(_____)         Last Modification : 1.5.0         (_____)

*/

ServerEvents.recipes(event => {

    //Recipes
    const recipes = [
        {
            result: 'tardis_refined:terraformer',
            pattern: [
                " TST ",
                " CQC ",
                " EHE ",
                " CDC ",
                " TST "
            ],
            key: {
                "T": 'mekanismgenerators:turbine_vent',
                "S": 'mekanism:steel_casing',
                "C": 'mekaevolution:cosmic_control_circuit',
                "Q": 'mekanism:quantum_entangloporter',
                "E": 'ae2:quantum_entangled_singularity',
                "H": 'techev_additions:chromatic',
                "D": 'mekanism:dimensional_stabilizer'
            }
        },
        {
            result: 'techev_additions:chromatic',
            pattern: [
                " UCU ",
                "UAHAU",
                "CHSHC",
                "UAHAU",
                " UCU "
            ],
            key: {
                "U": 'mysticalagriculture:ultimate_essence',
                "C": 'extendedcrafting:crystaltine_ingot',
                "A": 'mekanism:pellet_antimatter',
                "H": 'mekanism:pellet_hypermatter',
                "S": 'ae2:singularity',
            }
        },
        {
            result: 'productivebees:honeycomb_safenium',
            pattern: [
                "  A  ",
                " B*C ",
                "D* /d",
                " c/b ",
                "  a  "
            ],
            key: {
                "*": BeeConfigurableComb("inferium"),
                "/": BeeConfigurableComb("insanium"),
                "A": BeeConfigurableComb("geotic"),
                "B": BeeConfigurableComb("aquatic"),
                "C": BeeConfigurableComb("aeric"),
                "D": BeeConfigurableComb("magmatic"),
                "d": BeeConfigurableComb("gaia"),
                "c": BeeConfigurableComb("draconic"),
                "b": BeeConfigurableComb("starry"),
                "a": BeeConfigurableComb("nitro_crystal")
            }
        },
        {
            result: 'productivebees:honeycomb_sudentium',
            pattern: [
                "   ABC   ",
                "  DEFGH  ",
                " IJKLMNO ",
                "PQRS*TUVW",
                "XYZ* /zyx",
                "wvut/srqp",
                " onmlkji ",
                "  hgfed  ",
                "   cba   "
            ],
            key: {
                "*": BeeConfigurableComb("prudentium"),
                "/": BeeConfigurableComb("supremium"),
                "A": BeeConfigurableComb("copper"),
                "B": BeeConfigurableComb("niter"),
                "C": BeeConfigurableComb("aluminum"),
                "D": BeeConfigurableComb("osmium"),
                "E": BeeConfigurableComb("gold"),
                "F": BeeConfigurableComb("obsidian"),
                "G": BeeConfigurableComb("rabbit"),
                "H": 'productivebees:honeycomb_milky',
                "I": BeeConfigurableComb("prismarine"),
                "J": BeeConfigurableComb("zinc"),
                "K": BeeConfigurableComb("tin"),
                "L": BeeConfigurableComb("sulfur"),
                "M": BeeConfigurableComb("iron"),
                "N": BeeConfigurableComb("platinum"),
                "O": 'minecraft:honeycomb',
                "P": BeeConfigurableComb("nickel"),
                "Q": BeeConfigurableComb("chicken"),
                "R": BeeConfigurableComb("lead"),
                "S": BeeConfigurableComb("redstone"),
                "T": BeeConfigurableComb("coal"),
                "U": BeeConfigurableComb("silver"),
                "V": BeeConfigurableComb("radioactive"),
                "W": BeeConfigurableComb("glowing"),
                "X": BeeConfigurableComb("lapis"),
                "Y": BeeConfigurableComb("sheep"),
                "Z": BeeConfigurableComb("piggy"),
                "z": BeeConfigurableComb("calorite"),
                "y": BeeConfigurableComb("iridium"),
                "x": BeeConfigurableComb("lightning_dragonsteel"),
                "w": BeeConfigurableComb("spirited_crystal"),
                "v": BeeConfigurableComb("blizz"),
                "u": BeeConfigurableComb("elementium"),
                "t": BeeConfigurableComb("iesnium"),
                "s": BeeConfigurableComb("emerald"),
                "r": BeeConfigurableComb("enderium"),
                "q": BeeConfigurableComb("uraninite"),
                "p": BeeConfigurableComb("netherite"),
                "o": BeeConfigurableComb("fluix"),
                "n": BeeConfigurableComb("nephryx"),
                "m": BeeConfigurableComb("alfsteel"),
                "l": BeeConfigurableComb("diamond"),
                "k": BeeConfigurableComb("niotic_crystal"),
                "j": BeeConfigurableComb("wasted_radioactive"),
                "i": BeeConfigurableComb("blitz"),
                "h": BeeConfigurableComb("blazing"),
                "g": BeeConfigurableComb("terrasteel"),
                "f": BeeConfigurableComb("sculk"),
                "e": BeeConfigurableComb("plastic"),
                "d": BeeConfigurableComb("ice_dragonsteel"),
                "c": BeeConfigurableComb("basalz"),
                "b": BeeConfigurableComb("fire_dragonsteel"),
                "a": BeeConfigurableComb("awakened_supremium")
            }
        },
        {
            result: 'productivebees:honeycomb_impertium',
            pattern: [
                "   ABC   ",
                "  DEFGH  ",
                " IJKLMNO ",
                "PQRS*TUVW",
                "XYZ* /zyx",
                "wvut/srqp",
                " onmlkji ",
                "  hgfed  ",
                "   cba   "
            ],
            key: {
                "*": BeeConfigurableComb("tertium"),
                "/": BeeConfigurableComb("imperium"),
                "A": BeeConfigurableComb("spirit"),
                "B": BeeConfigurableComb("experience"),
                "C": BeeConfigurableComb("amethyst"),
                "D": BeeConfigurableComb("arcane"),
                "E": BeeConfigurableComb("cinnabar"),
                "F": BeeConfigurableComb("hop_graphite"),
                "G": BeeConfigurableComb("ruby"),
                "H": BeeConfigurableComb("turtle"),
                "I": BeeConfigurableComb("sapphire"),
                "J": BeeConfigurableComb("silicon"),
                "K": BeeConfigurableComb("oily"),
                "L": BeeConfigurableComb("zombie"),
                "M": BeeConfigurableComb("skeletal"),
                "N": BeeConfigurableComb("slimy"),
                "O": BeeConfigurableComb("peridot"),
                "P": BeeConfigurableComb("fishy"),
                "Q": BeeConfigurableComb("spacial"),
                "R": BeeConfigurableComb("ironwood"),
                "S": BeeConfigurableComb("knightmetal"),
                "T": BeeConfigurableComb("tea"),
                "U": BeeConfigurableComb("fiery"),
                "V": BeeConfigurableComb("steeleaf"),
                "W": BeeConfigurableComb("apatite"),
                "X": BeeConfigurableComb("crystalline"),
                "Y": BeeConfigurableComb("squid"),
                "Z": BeeConfigurableComb("chocolate"),
                "z": BeeConfigurableComb("destabilized_redstone"),
                "y": BeeConfigurableComb("compressed_iron"),
                "x": BeeConfigurableComb("ostrum"),
                "w": BeeConfigurableComb("fluorite"),
                "v": BeeConfigurableComb("resonant_ender"),
                "u": BeeConfigurableComb("energized_glowstone"),
                "t": BeeConfigurableComb("withered"),
                "s": BeeConfigurableComb("refined_obsidian"),
                "r": BeeConfigurableComb("constantan"),
                "q": BeeConfigurableComb("pink_slimy"),
                "p": BeeConfigurableComb("steel"),
                "o": BeeConfigurableComb("silky"),
                "n": BeeConfigurableComb("energized_steel"),
                "m": BeeConfigurableComb("signalum"),
                "l": BeeConfigurableComb("bronze"),
                "k": BeeConfigurableComb("desh"),
                "j": BeeConfigurableComb("electrum"),
                "i": BeeConfigurableComb("ender"),
                "h": BeeConfigurableComb("manasteel"),
                "g": BeeConfigurableComb("refined_glowstone"),
                "f": BeeConfigurableComb("invar"),
                "e": BeeConfigurableComb("brass"),
                "d": BeeConfigurableComb("lumium"),
                "c": BeeConfigurableComb("blazing_crystal"),
                "b": 'productivebees:honeycomb_ghostly',
                "a": 'productivebees:honeycomb_powdery'
            }
        },
        {
            result: 'extendedcrafting:ultimate_singularity',
            pattern: [
                "ABCBCBA",
                "BDEFGHB",
                "CIJKLMC",
                "BNOPQRB",
                "CSTUVWC",
                "BXYZabB",
                "ABCBCBA"
            ],
            key: {
                "A": 'ftbic:antimatter_crystal',
                "B": 'ftbic:singularity_ash',
                "C": 'ftbic:antimatter',
                "D": Singularity("iron"),
                "E": Singularity("aluminum"),
                "F": Singularity("silver"),
                "G": Singularity("froststeel"),
                "H": Singularity("iridium"),
                "I": Singularity("desh"),
                "J": Singularity("copper"),
                "K": Singularity("horizonite"),
                "L": Singularity("calorite"),
                "M": Singularity("lead"),
                "N": Singularity("gold"),
                "O": Singularity("cloggrum"),
                "P": "enigmaticlegacy:cosmic_heart",
                "Q": Singularity("ventium"),
                "R": Singularity("iesnium"),
                "S": Singularity("nickel"),
                "T": Singularity("falsite"),
                "U": Singularity("elementium"),
                "V": Singularity("ostrum"),
                "W": Singularity("platinum"),
                "X": Singularity("uranium"),
                "Y": Singularity("nephryx"),
                "Z": Singularity("zinc"),
                "a": Singularity("tin"),
                "b": Singularity("osmium")
            }
        },
        {
            result: 'techev_additions:complex_plate',
            pattern: [
                "    ABC  ",
                "   DEFGH ",
                "  IJKLMNO",
                " PQRSTUVW",
                "XYZabcdef",
                "ghijklmn ",
                "opqrstu  ",
                " vwxyz   ",
                "  012    "
            ],
            key: {
                "A": "alltheores:diamond_plate",
                "B": "alltheores:enderium_plate",
                "C": "occultism:iesnium_plate",
                "D": "alltheores:iridium_plate",
                "E": "alltheores:invar_plate",
                "F": "alltheores:tin_plate",
                "G": "alltheores:osmium_plate",
                "H": "alltheores:platinum_plate",
                "I": "alltheores:aluminum_plate",
                "J": "alltheores:iron_plate",
                "K": "alltheores:steel_plate",
                "L": "alltheores:silver_plate",
                "M": "alltheores:lead_plate",
                "N": "thermal_extra:dragonsteel_plate",
                "O": "create_things_and_misc:blue_quartz_sheet",
                "P": "thermalendergy:stellarium_plate",
                "Q": "create_new_age:overcharged_iron_sheet",
                "R": "thermal:netherite_plate",
                "S": "pneumaticcraft:compressed_iron_plate",
                "T": "undergarden:froststeel_plate",
                "U": "create_things_and_misc:source_quartz_sheet",
                "V": "thermalendergy:melodium_plate",
                "W": "blue_skies:falsite_plate",
                "X": "alltheores:uranium_plate",
                "Y": "alltheores:zinc_plate",
                "Z": "thermalendergy:prismalium_plate",
                "a": "createdeco:cast_iron_sheet",
                "b": "chemlib:tellurium",
                "c": "create_things_and_misc:psi_quartz_sheet",
                "d": "create_things_and_misc:antimatter_quartz_sheet",
                "e": "botania:elementium_plate",
                "f": "thermal_extra:shellite_plate",
                "g": "ad_astra:nephryx_plate",
                "h": "create_things_and_misc:experience_sheet",
                "i": "alltheores:nickel_plate",
                "j": "ftbic:carbon_plate",
                "k": "ad_astra:ostrum_plate",
                "l": "create_things_and_misc:rose_quartz_sheet",
                "m": "ad_astra:calorite_plate",
                "n": "blue_skies:ventium_plate",
                "o": "alltheores:brass_plate",
                "p": "alltheores:lumium_plate",
                "q": "alltheores:electrum_plate",
                "r": "undergarden:cloggrum_plate",
                "s": "thermal_extra:twinite_plate",
                "t": "blue_skies:horizonite_plate",
                "u": "alltheores:signalum_plate",
                "v": "create_new_age:overcharged_golden_sheet",
                "w": "thermal_extra:soul_infused_plate",
                "x": "alltheores:constantan_plate",
                "y": "eidolon:arcane_gold_plate",
                "z": "alltheores:copper_plate",
                "0": "alltheores:gold_plate",
                "1": "ad_astra:desh_plate",
                "2": "alltheores:bronze_plate"
            }
        },
        {
            result: 'techev_additions:complex_gear',
            pattern: [
                "AB  C  DE",
                "FG HIJ KL",
                "  MNOPQ  ",
                " RSTUVWX ",
                "YZab bcde",
                " fghijkl ",
                "  mnopq  ",
                "rs tuv wx",
                "yz  0  12"
            ],
            key: {
                "A": "blue_skies:falsite_gear",
                "B": "thermalendergy:melodium_gear",
                "C": "thermal_extra:dragonsteel_gear",
                "D": "alltheores:enderium_gear",
                "E": "alltheores:diamond_gear",
                "F": "create_things_and_misc:antimatter_quartz_gear",
                "G": "botania:elementium_gear",
                "H": "undergarden:froststeel_gear",
                "I": "alltheores:lead_gear",
                "J": "create_things_and_misc:psi_quartz_gear",
                "K": "alltheores:aluminum_gear",
                "L": "alltheores:platinum_gear",
                "M": "create_things_and_misc:source_quartz_gear",
                "N": "alltheores:invar_gear",
                "O": "thermalendergy:stellarium_gear",
                "P": "create_things_and_misc:blue_quartz_gear",
                "Q": "alltheores:osmium_gear",
                "R": "ad_astra:calorite_gear",
                "S": "thermal_extra:shellite_gear",
                "T": "alltheores:silver_gear",
                "U": "alltheores:iridium_gear",
                "V": "alltheores:tin_gear",
                "W": "occultism:iesnium_gear",
                "X": "thermalendergy:prismalium_gear",
                "Y": "blue_skies:horizonite_gear",
                "Z": "alltheores:signalum_gear",
                "a": "blue_skies:ventium_gear",
                "b": "chemlib:tellurium",
                "c": "create_things_and_misc:experience_gear",
                "d": "alltheores:zinc_gear",
                "e": "alltheores:uranium_gear",
                "f": "create_things_and_misc:rose_quartz_gear",
                "g": "thermal_extra:twinite_gear",
                "h": "ad_astra:ostrum_gear",
                "i": "alltheores:constantan_gear",
                "j": "alltheores:nickel_gear",
                "k": "alltheores:copper_gear",
                "l": "ad_astra:nephryx_gear",
                "m": "eidolon:arcane_gold_gear",
                "n": "alltheores:bronze_gear",
                "o": "thermal_extra:soul_infused_gear",
                "p": "ad_astra:desh_gear",
                "q": "create_new_age:overcharged_iron_gear",
                "r": "alltheores:gold_gear",
                "s": "alltheores:electrum_gear",
                "t": "alltheores:brass_gear",
                "u": "undergarden:cloggrum_gear",
                "v": "alltheores:iron_gear",
                "w": "alltheores:steel_gear",
                "x": "thermal:netherite_gear",
                "y": "create_new_age:overcharged_golden_gear",
                "z": "alltheores:lumium_gear",
                "0": "createdeco:cast_iron_gear",
                "1": "pneumaticcraft:compressed_iron_gear",
                "2": "ftbic:carbon_gear"
            }
        },
        {
            result: 'techev_additions:complex_rod',
            pattern: [
                "     ABCD",
                "   EFGHIJ",
                "   KLMNOP",
                " QRSTUVWX",
                " YZabcde ",
                "fghijklm ",
                "nopqrs   ",
                "tuvwxy   ",
                "z012     "
            ],
            key: {
                "A": "alltheores:lead_rod",
                "B": "thermal_extra:dragonsteel_rod",
                "C": "alltheores:enderium_rod",
                "D": "alltheores:diamond_rod",
                "E": "botania:elementium_rod",
                "F": "thermal_extra:shellite_rod",
                "G": "create_things_and_misc:source_quartz_rod",
                "H": "alltheores:iridium_rod",
                "I": "create_things_and_misc:blue_quartz_rod",
                "J": "alltheores:osmium_rod",
                "K": "blue_skies:falsite_rod",
                "L": "create_things_and_misc:antimatter_quartz_rod",
                "M": "thermalendergy:melodium_rod",
                "N": "create_things_and_misc:psi_quartz_rod",
                "O": "alltheores:aluminum_rod",
                "P": "undergarden:froststeel_rod",
                "Q": "pneumaticcraft:compressed_iron_rod",
                "R": "createdeco:cast_iron_rod",
                "S": "thermal:netherite_rod",
                "T": "ftbic:carbon_rod",
                "U": "alltheores:silver_rod",
                "V": "alltheores:invar_rod",
                "W": "alltheores:tin_rod",
                "X": "alltheores:platinum_rod",
                "Y": "create_new_age:overcharged_iron_rod",
                "Z": "alltheores:iron_rod",
                "a": "alltheores:steel_rod",
                "b": "chemlib:tellurium",
                "c": "ad_astra:nephryx_rod",
                "d": "thermalendergy:prismalium_rod",
                "e": "occultism:iesnium_rod",
                "f": "alltheores:lumium_rod",
                "g": "create_new_age:overcharged_golden_rod",
                "h": "alltheores:gold_rod",
                "i": "alltheores:constantan_rod",
                "j": "undergarden:cloggrum_rod",
                "k": "alltheores:zinc_rod",
                "l": "alltheores:uranium_rod",
                "m": "thermalendergy:stellarium_rod",
                "n": "alltheores:nickel_rod",
                "o": "eidolon:arcane_gold_rod",
                "p": "alltheores:copper_rod",
                "q": "alltheores:brass_rod",
                "r": "thermal_extra:soul_infused_rod",
                "s": "create_things_and_misc:experience_rod",
                "t": "ad_astra:ostrum_rod",
                "u": "thermal_extra:twinite_rod",
                "v": "create_things_and_misc:rose_quartz_rod",
                "w": "blue_skies:horizonite_rod",
                "x": "alltheores:bronze_rod",
                "y": "alltheores:electrum_rod",
                "z": "ad_astra:desh_rod",
                "0": "ad_astra:calorite_rod",
                "1": "alltheores:signalum_rod",
                "2": "blue_skies:ventium_rod"
            }
        },
        {
            result: 'techev_additions:complex_dust',
            pattern: [
                "    A    ",
                "   BCD   ",
                "  EFGHI  ",
                " JKLMNOP ",
                "QRSTUVWXY",
                "Zabcdefgh",
                "ijklmnopq",
                " rstuvwx ",
                "  yz012  "
            ],
            key: {
                "A": "occultism:iesnium_dust",
                "B": "alltheores:diamond_dust",
                "C": "alltheores:enderium_dust",
                "D": "thermal_extra:dragonsteel_dust",
                "E": "undergarden:froststeel_dust",
                "F": "create_things_and_misc:blue_quartz_dust",
                "G": "create_things_and_misc:psi_quartz_dust",
                "H": "alltheores:lead_dust",
                "I": "thermal_extra:twinite_dust",
                "J": "alltheores:osmium_dust",
                "K": "thermalendergy:stellarium_dust",
                "L": "thermal_extra:shellite_dust",
                "M": "botania:elementium_dust",
                "N": "thermalendergy:melodium_dust",
                "O": "ad_astra:calorite_dust",
                "P": "blue_skies:ventium_dust",
                "Q": "ad_astra:nephryx_dust",
                "R": "create_things_and_misc:experience_dust",
                "S": "alltheores:zinc_dust",
                "T": "create_things_and_misc:source_quartz_dust",
                "U": "create_things_and_misc:antimatter_quartz_dust",
                "V": "blue_skies:horizonite_dust",
                "W": "create_things_and_misc:rose_quartz_dust",
                "X": "alltheores:signalum_dust",
                "Y": "alltheores:bronze_dust",
                "Z": "alltheores:invar_dust",
                "a": "alltheores:uranium_dust",
                "b": "thermalendergy:prismalium_dust",
                "c": "blue_skies:falsite_dust",
                "d": "chemlib:tellurium",
                "e": "create_new_age:overcharged_golden_dust",
                "f": "alltheores:gold_dust",
                "g": "alltheores:lumium_dust",
                "h": "alltheores:brass_dust",
                "i": "alltheores:tin_dust",
                "j": "alltheores:aluminum_dust",
                "k": "alltheores:platinum_dust",
                "l": "ad_astra:ostrum_dust",
                "m": "alltheores:steel_dust",
                "n": "eidolon:arcane_gold_dust",
                "o": "alltheores:nickel_dust",
                "p": "ad_astra:desh_dust",
                "q": "alltheores:constantan_dust",
                "r": "alltheores:iridium_dust",
                "s": "alltheores:silver_dust",
                "t": "pneumaticcraft:compressed_iron_dust",
                "u": "alltheores:netherite_dust",
                "v": "alltheores:copper_dust",
                "w": "thermal_extra:soul_infused_dust",
                "x": "alltheores:electrum_dust",
                "y": "create_new_age:overcharged_iron_dust",
                "z": "alltheores:iron_dust",
                "0": "ftbic:carbon_dust",
                "1": "createdeco:cast_iron_dust",
                "2": "undergarden:cloggrum_dust"
            }
        },
        {
            result: 'techev_additions:tellurite',
            pattern: [
                "  ABA  ",
                " CDEDC ",
                "ADFGFDA",
                "BEGHGEB",
                "ADFGFDA",
                " CDEDC ",
                "  ABA  "
            ],
            key: {
                "A": "extendedcrafting:flux_star",
                "B": "techev_additions:complex_mechanism",
                "C": "techev_additions:complex_gear",
                "D": "chemlib:tellurium",
                "E": "techev_additions:complex_dust",
                "F": "techev_additions:complex_rod",
                "G": "techev_additions:complex_plate",
                "H": "extendedcrafting:ultimate_singularity"
            }
        }
    ]

    //General Shaped Function
    recipes.forEach((recipe) => {
        let json = {
            type: 'extendedcrafting:shaped_table',
            pattern: recipe.pattern,
            key: recipe.key,
            result: parseIngredient(recipe.result)
        }
        event.custom(json).id(`extendedcrafting:${recipe.result.split(":")[1]}`)
    })
})