#Need help? Ask on Discord or Github/Gitlab <3 (ps: it is possible that this file contains nothing it's normal)
<<<<<<< HEAD
#Tue Jan 27 23:29:46 CET 2026
=======
#Sat Feb 14 22:04:55 CET 2026
>>>>>>> 1.5.x
boolean.creative.enable_item_group_ferret=false
