#Need help? Ask on Discord or Github/Gitlab <3 (ps: it is possible that this file contains nothing it's normal)
<<<<<<< HEAD
#Sun Sep 14 16:43:33 CEST 2025
=======
#Tue Sep 30 18:49:23 CEST 2025
>>>>>>> 1.4.x
boolean.creative.enable_item_group_ferret=false
