#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Oct 12 13:29:13 CEST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=16
shaderPack=
enableShaders=true
