#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Oct 22 11:42:45 CEST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=16
shaderPack=
enableShaders=true
