#This file stores configuration options for Iris, such as the currently active shaderpack
<<<<<<< HEAD
#Sun Sep 14 16:44:18 CEST 2025
=======
#Tue Sep 30 18:50:01 CEST 2025
>>>>>>> 1.4.x
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=16
shaderPack=
enableShaders=true
